[server]
headless = true
fileWatcherType = "poll"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false